"use client";

import { useState, useMemo } from "react";

// Curated English word list for crossword-relevant anagram solving (3-8 letters)
const WORD_LIST = [
  // 3-letter
  "ACE","ACT","ADD","AGE","AGO","AID","AIM","AIR","ALE","ALL","AND","ANT","APE","ARC","ARE","ARK","ARM","ART","ASH","ATE","AWE","AXE",
  "BAD","BAG","BAN","BAR","BAT","BAY","BED","BET","BIG","BIT","BOW","BOX","BOY","BUD","BUG","BUN","BUS","BUT","BUY",
  "CAB","CAN","CAP","CAR","CAT","COP","COT","COW","CRY","CUB","CUP","CUR","CUT",
  "DAM","DAY","DEN","DEW","DID","DIG","DIM","DIP","DOC","DOE","DOG","DOT","DRY","DUB","DUE","DUG","DUN","DUO","DYE",
  "EAR","EAT","EEL","EGG","ELF","ELK","ELM","EMU","END","ERA","ERR","EVE","EWE","EYE",
  "FAN","FAR","FAT","FAX","FED","FEE","FEN","FEW","FIG","FIN","FIR","FIT","FIX","FLU","FLY","FOB","FOE","FOG","FOP","FOR","FOX","FRY","FUN","FUR",
  "GAB","GAG","GAP","GAS","GAY","GEL","GEM","GET","GIG","GIN","GNU","GOB","GOD","GOT","GUM","GUN","GUT","GUY","GYM",
  "HAD","HAM","HAS","HAT","HAY","HEN","HER","HEW","HID","HIM","HIP","HIS","HIT","HOB","HOD","HOG","HOP","HOT","HOW","HUB","HUE","HUG","HUM","HUT",
  "ICE","ICY","ILL","IMP","INK","INN","ION","IRE","IRK","ITS","IVY",
  "JAB","JAG","JAM","JAR","JAW","JAY","JET","JIG","JOB","JOG","JOT","JOY","JUG","JUT",
  "KEG","KEN","KEY","KID","KIN","KIT",
  "LAB","LAD","LAG","LAP","LAW","LAY","LEA","LED","LEG","LET","LID","LIE","LIP","LIT","LOG","LOT","LOW",
  "MAD","MAN","MAP","MAR","MAT","MAW","MAY","MEN","MET","MID","MIX","MOB","MOD","MOP","MOW","MUD","MUG","MUM",
  "NAB","NAG","NAP","NET","NEW","NIL","NIT","NOB","NOD","NOR","NOT","NOW","NUB","NUN","NUT",
  "OAK","OAR","OAT","ODD","ODE","OFF","OFT","OIL","OLD","ONE","OPT","ORB","ORE","OUR","OUT","OWE","OWL","OWN",
  "PAD","PAL","PAN","PAP","PAR","PAT","PAW","PAY","PEA","PEG","PEN","PER","PET","PEW","PIE","PIG","PIN","PIT","PLY","POD","POP","POT","POW","PRY","PUB","PUG","PUN","PUP","PUS","PUT",
  "RAG","RAM","RAN","RAP","RAT","RAW","RAY","RED","REF","RIB","RID","RIG","RIM","RIP","ROB","ROD","ROE","ROT","ROW","RUB","RUG","RUM","RUN","RUT","RYE",
  "SAC","SAD","SAG","SAP","SAT","SAW","SAY","SEA","SET","SEW","SHE","SHY","SIN","SIP","SIR","SIS","SIT","SIX","SKI","SKY","SLY","SOB","SOD","SON","SOP","SOT","SOW","SOY","SPA","SPY","STY","SUB","SUM","SUN","SUP",
  "TAB","TAD","TAG","TAN","TAP","TAR","TAT","TAX","TEA","TEN","THE","TIE","TIN","TIP","TOE","TON","TOO","TOP","TOT","TOW","TOY","TRY","TUB","TUG","TUN","TWO",
  "URN","USE",
  "VAN","VAT","VET","VEX","VIA","VIE","VOW",
  "WAD","WAG","WAR","WAS","WAX","WAY","WEB","WED","WET","WHO","WIG","WIN","WIT","WOE","WOK","WON","WOO","WOW",
  "YAK","YAM","YAP","YAW","YEA","YES","YET","YEW","YOU","YOW",
  "ZAP","ZEN","ZIP","ZIT","ZOO",
  // 4-letter
  "ABLE","ACHE","ACID","ACRE","AGED","AIDE","ALOE","ALSO","ARCH","AREA","ARIA","ARMY","ARTS","AXLE",
  "BADE","BAIT","BAKE","BALD","BALE","BALM","BAND","BANE","BANK","BARE","BARK","BARN","BASE","BATH","BEAD","BEAM","BEAN","BEAR","BEAT","BELL","BELT","BEND","BEST","BIKE","BIND","BIRD","BITE","BLOT","BLOW","BLUE","BLUR","BOAR","BOAT","BOLD","BOLT","BOMB","BOND","BONE","BOOK","BOOM","BOOT","BORE","BORN","BOSS","BOTH","BOWL","BRIM","BULK","BULL","BURN","BUST",
  "CAFE","CAGE","CAKE","CALF","CALL","CALM","CAME","CAMP","CANE","CAPE","CARD","CARE","CART","CASE","CASH","CAST","CAVE","CHAR","CHIN","CHIP","CHOP","CITE","CITY","CLAD","CLAM","CLAN","CLAP","CLAW","CLAY","CLIP","CLOD","CLOT","CLUB","CLUE","COAL","COAT","CODE","COIL","COIN","COLD","COLT","COMB","COME","CONE","COOK","COOL","COPE","COPY","CORD","CORE","CORK","CORN","COST","COSY","COUP","COVE","CRAB","CREW","CROP","CROW","CUBE","CULT","CURB","CURE","CURL","CUTE",
  "DALE","DAME","DAMP","DARE","DARK","DARN","DART","DASH","DATA","DATE","DAWN","DEAD","DEAF","DEAL","DEAR","DEBT","DECK","DEED","DEEM","DEEP","DEER","DEFT","DENY","DESK","DICE","DIET","DINE","DIRE","DIRT","DISC","DISH","DOCK","DOES","DOME","DONE","DOOM","DOOR","DOSE","DOTE","DOWN","DOZE","DRAB","DRAG","DRAW","DREW","DRIP","DROP","DRUM","DUAL","DUEL","DULL","DUMB","DUMP","DUNE","DUSK","DUST","DUTY",
  "EACH","EARL","EARN","EASE","EAST","EASY","ECHO","EDGE","EDIT","ELSE","EMIT","EPIC","EVEN","EVER","EVIL","EXAM","EXIT","EYED",
  "FACE","FACT","FADE","FAIL","FAIR","FAKE","FALL","FAME","FANG","FARE","FARM","FAST","FATE","FAWN","FEAR","FEAT","FEED","FEEL","FELL","FELT","FERN","FEST","FILE","FILL","FILM","FIND","FINE","FIRE","FIRM","FISH","FIST","FLAG","FLAP","FLAT","FLAW","FLEA","FLED","FLEW","FLIP","FLIT","FLOG","FLOW","FOAM","FOIL","FOLD","FOLK","FOND","FONT","FOOD","FOOL","FOOT","FORD","FORE","FORK","FORM","FORT","FOUL","FOUR","FOWL","FREE","FROG","FROM","FUEL","FULL","FUME","FUND","FUSE","FUSS",
  "GAIT","GALE","GAME","GANG","GAPE","GARB","GATE","GAVE","GAZE","GEAR","GENE","GIFT","GILD","GILT","GIRL","GIST","GIVE","GLAD","GLEN","GLOW","GLUE","GLUM","GNAT","GNAW","GOAL","GOAT","GOES","GOLD","GOLF","GONE","GOOD","GORE","GRAB","GRAM","GRAY","GREW","GRID","GRIM","GRIN","GRIP","GRIT","GROG","GROW","GULF","GUST","GUTS",
  "HACK","HAIL","HAIR","HALE","HALF","HALL","HALT","HAND","HANG","HARE","HARM","HARP","HART","HASH","HATE","HAUL","HAVE","HAWK","HAZE","HAZY","HEAD","HEAL","HEAP","HEAR","HEAT","HEED","HEEL","HELD","HELM","HELP","HERB","HERD","HERE","HERO","HIDE","HIGH","HIKE","HILL","HILT","HIND","HINT","HIRE","HOLD","HOLE","HOME","HONE","HOOD","HOOF","HOOK","HOPE","HORN","HOST","HOUR","HOWL","HUGE","HULL","HUMP","HUNG","HUNT","HURL","HURT","HUSH","HYMN",
  "ICON","IDEA","IDLE","IDOL","INCH","INTO","IRON","ISLE","ITEM",
  "JADE","JAIL","JAMB","JAPE","JAZZ","JEST","JILT","JOIN","JOKE","JOLT","JOWL","JUDO","JUMP","JURY","JUST","JUTE",
  "KALE","KEEN","KEEP","KELP","KEPT","KILT","KIND","KING","KINK","KITE","KNEE","KNEW","KNIT","KNOB","KNOT","KNOW",
  "LACE","LACK","LACY","LAID","LAIR","LAKE","LAME","LAMP","LAND","LANE","LANK","LARD","LARK","LASH","LASS","LAST","LATE","LATH","LAWN","LAZY","LEAD","LEAF","LEAK","LEAN","LEAP","LEFT","LEND","LENS","LENT","LESS","LEST","LEVY","LIAR","LICE","LICK","LIED","LIEU","LIFE","LIFT","LIKE","LIMB","LIME","LIMP","LINE","LINK","LINT","LION","LIST","LIVE","LOAD","LOAF","LOAM","LOAN","LOBE","LOCK","LODE","LOFT","LOGO","LONE","LONG","LOOK","LOOM","LOOP","LOOT","LORD","LORE","LOSE","LOSS","LOST","LOTS","LOUD","LOVE","LUCK","LULL","LUMP","LURE","LURK","LUSH","LUTE",
  "MACE","MADE","MAID","MAIL","MAIN","MAKE","MALE","MALT","MANE","MANY","MARE","MARK","MARS","MASH","MASK","MASS","MAST","MATE","MAZE","MEAD","MEAL","MEAN","MEAT","MEEK","MEET","MELD","MELT","MEMO","MEND","MENU","MERE","MESH","MESS","MICE","MILD","MILE","MILK","MILL","MIME","MIND","MINE","MINT","MIRE","MISS","MIST","MITE","MOAT","MOCK","MODE","MOLE","MOLT","MONK","MOOD","MOON","MOOR","MORE","MOSS","MOST","MOTH","MOVE","MUCH","MUCK","MULE","MULL","MUSE","MUSH","MUST","MUTE",
  "NAIL","NAME","NAVE","NAVY","NEAR","NEAT","NECK","NEED","NEST","NEWS","NEXT","NICE","NINE","NODE","NONE","NOON","NORM","NOSE","NOTE","NOUN","NUDE","NULL",
  "OATH","OBEY","ODOR","OGLE","OGRE","OMEN","OMIT","ONCE","ONLY","ONTO","OOZE","OPEN","OPUS","ORAL","ORCA","OVAL","OVEN","OVER","OWED","OXEN",
  "PACE","PACK","PACT","PAGE","PAID","PAIL","PAIN","PAIR","PALE","PALM","PANE","PANG","PARK","PART","PASS","PAST","PATH","PAVE","PAWN","PEAK","PEAL","PEAR","PEAT","PECK","PEEL","PEER","PELT","PEND","PENT","PERK","PEST","PICK","PIER","PIKE","PILE","PILL","PINE","PINK","PINT","PIPE","PITY","PLAN","PLAY","PLEA","PLOD","PLOT","PLOW","PLOY","PLUG","PLUM","PLUS","POCK","POEM","POET","POKE","POLE","POLL","POLO","POMP","POND","PONY","POOL","POOR","POPE","PORE","PORK","PORT","POSE","POSH","POST","POUR","PRAY","PREY","PRIG","PRIM","PROD","PROP","PROW","PUCK","PULL","PULP","PUMP","PUNK","PURE","PUSH",
  "QUIT","QUIZ",
  "RACE","RACK","RAFT","RAGE","RAID","RAIL","RAIN","RAKE","RAMP","RANG","RANK","RANT","RARE","RASH","RASP","RATE","RAVE","READ","REAL","REAM","REAP","REAR","REED","REEF","REEL","REIN","RELY","REND","RENT","REST","RICH","RIDE","RIFT","RILE","RILL","RIME","RIND","RING","RIOT","RISE","RISK","ROAD","ROAM","ROAR","ROBE","ROCK","RODE","ROLE","ROLL","ROOF","ROOM","ROOT","ROPE","ROSE","ROSY","ROUT","ROVE","RUDE","RUIN","RULE","RUNG","RUSE","RUSH","RUST",
  "SACK","SAFE","SAGE","SAID","SAIL","SAKE","SALE","SALT","SAME","SAND","SANE","SANG","SANK","SASH","SAVE","SCAN","SCAR","SEAL","SEAM","SEAR","SEAT","SECT","SEED","SEEK","SEEM","SEEN","SELF","SELL","SEMI","SEND","SENT","SHED","SHIN","SHIP","SHOE","SHOP","SHOT","SHOW","SHUN","SHUT","SICK","SIDE","SIGH","SIGN","SILK","SILL","SILO","SILT","SINE","SING","SINK","SIRE","SITE","SIZE","SLAB","SLAG","SLAM","SLAP","SLAT","SLED","SLEW","SLID","SLIM","SLIP","SLIT","SLOB","SLOP","SLOT","SLOW","SLUG","SLUM","SLUR","SMOG","SNAP","SNIP","SNOB","SNOW","SNUB","SNUG","SOAK","SOAP","SOAR","SOCK","SODA","SOFA","SOFT","SOIL","SOLD","SOLE","SOLO","SOME","SONG","SOON","SOOT","SORE","SORT","SOUL","SOUR","SPAN","SPAR","SPED","SPIN","SPIT","SPOT","SPUR","STAB","STAG","STAR","STAY","STEM","STEP","STEW","STIR","STOP","STOW","STUB","STUD","STUN","SWAY","SWIM",
  "TACK","TACT","TAIL","TAKE","TALE","TALK","TALL","TAME","TANG","TANK","TAPE","TARN","TART","TASK","TAXI","TEAK","TEAL","TEAM","TEAR","TELL","TEND","TENT","TERM","TEST","TEXT","THAN","THAT","THEM","THEN","THEY","THIN","THIS","THUD","THUS","TICK","TIDE","TIDY","TIED","TIER","TILE","TILL","TILT","TIME","TINE","TINY","TIRE","TOAD","TOIL","TOLD","TOLL","TOMB","TOME","TONE","TOOK","TOOL","TORE","TORN","TORT","TOSS","TOUR","TOWN","TRAP","TRAY","TREE","TREK","TRIM","TRIO","TRIP","TROD","TROT","TRUE","TUBE","TUCK","TUFT","TUNA","TUNE","TURF","TURN","TUSK","TWIN","TYPE",
  "UGLY","UNDO","UNIT","UNTO","UPON","URGE","USED","USER",
  "VAIN","VALE","VANE","VARY","VASE","VAST","VEER","VEIL","VEIN","VENT","VERB","VERY","VEST","VETO","VICE","VIEW","VILE","VINE","VISA","VOID","VOLT","VOTE",
  "WADE","WAGE","WAIL","WAIT","WAKE","WALK","WALL","WAND","WANT","WARD","WARM","WARN","WARP","WART","WARY","WASH","WASP","WAVE","WAVY","WAXY","WEAK","WEAN","WEAR","WEED","WEEK","WEEP","WELD","WELL","WENT","WERE","WEST","WHAT","WHEN","WHIM","WHIP","WHOM","WICK","WIDE","WIFE","WILD","WILL","WILT","WILY","WIMP","WIND","WINE","WING","WINK","WIPE","WIRE","WISE","WISH","WISP","WITH","WOKE","WOLF","WOMB","WOOD","WOOL","WORD","WORE","WORK","WORM","WORN","WOVE","WRAP","WREN","WRIT",
  "YANK","YARD","YARN","YEAR","YELL","YOGA","YOKE","YOUR",
  "ZEAL","ZERO","ZEST","ZINC","ZONE","ZOOM",
  // 5-letter
  "ABIDE","ABOUT","ABOVE","ABUSE","ADMIT","ADOPT","ADORE","ADULT","AGENT","AGILE","AGING","AGREE","AHEAD","AISLE","ALARM","ALBUM","ALERT","ALIEN","ALIGN","ALIVE","ALLEY","ALLOW","ALLOY","ALONE","ALONG","ALTER","AMPLE","ANGEL","ANGER","ANGLE","ANGRY","ANIME","ANKLE","ANNEX","ANTIC","APART","APPLY","ARENA","ARGUE","ARISE","ARMOR","AROMA","AROSE","ASIDE","ASSET","ATONE","AUDIO","AVAIL","AVOID","AWAIT","AWAKE","AWARD","AWARE","AWFUL",
  "BADGE","BASIN","BASIS","BATCH","BEACH","BEARD","BEAST","BEGIN","BEING","BELOW","BENCH","BIBLE","BIRTH","BLACK","BLADE","BLAME","BLAND","BLANK","BLAST","BLAZE","BLEAK","BLEED","BLEND","BLESS","BLIND","BLINK","BLISS","BLOCK","BLOND","BLOOM","BLOWN","BOARD","BOAST","BONUS","BOOST","BOOTH","BOUND","BRAVE","BREAD","BREAK","BREED","BRICK","BRIDE","BRIEF","BRING","BROAD","BROKE","BROOK","BROWN","BRUSH","BUILD","BUNCH","BURST","BUYER",
  "CABIN","CABLE","CANDY","CARGO","CARRY","CATCH","CATER","CAUSE","CHAIN","CHAIR","CHALK","CHAMP","CHAOS","CHARM","CHART","CHASE","CHEAP","CHEAT","CHECK","CHEEK","CHEER","CHESS","CHEST","CHIEF","CHILD","CHINA","CHOIR","CHORD","CHOSE","CHUNK","CLAIM","CLASH","CLASS","CLEAN","CLEAR","CLERK","CLIFF","CLIMB","CLING","CLOCK","CLONE","CLOSE","CLOTH","CLOUD","COACH","COAST","COLOR","COMET","COMIC","CORAL","COUNT","COURT","COVER","CRACK","CRAFT","CRANE","CRASH","CRAWL","CRAZY","CREAM","CREST","CRIME","CRISP","CROSS","CROWD","CROWN","CRUDE","CRUEL","CRUSH","CURVE","CYCLE",
  "DAILY","DANCE","DEATH","DEBUT","DELAY","DELTA","DEMON","DEPOT","DEPTH","DERBY","DEVIL","DIGIT","DIRTY","DOUBT","DOUGH","DRAFT","DRAIN","DRAKE","DRAMA","DRANK","DRAWN","DREAM","DRESS","DRIED","DRIFT","DRILL","DRINK","DRIVE","DROWN","EAGER","EARTH","EIGHT","ELECT","ELITE","EMBED","EMOTE","EMPTY","ENDOW","ENEMY","ENJOY","ENTER","ENTRY","EQUAL","EQUIP","ERASE","ERROR","EVENT","EVERY","EVOKE","EXACT","EXILE","EXIST","EXPEL","EXTRA",
  "FABLE","FACET","FAITH","FALSE","FANCY","FATAL","FAULT","FEAST","FERRY","FEVER","FIBER","FIELD","FIFTY","FIGHT","FINAL","FLAME","FLASH","FLEET","FLESH","FLOAT","FLOCK","FLOOD","FLOOR","FLORA","FLOUR","FLUID","FLUSH","FOCAL","FOCUS","FORCE","FORGE","FORTH","FORUM","FOUND","FRAME","FRANK","FRAUD","FRESH","FRONT","FROST","FRUIT","FULLY","FUNDS",
  "GIANT","GIVEN","GLARE","GLASS","GLEAM","GLOBE","GLOOM","GLORY","GLOSS","GLOVE","GRACE","GRADE","GRAIN","GRAND","GRANT","GRAPE","GRAPH","GRASP","GRASS","GRAVE","GREAT","GREEN","GREET","GRIEF","GRILL","GRIND","GROAN","GROOM","GROSS","GROUP","GROVE","GROWN","GUARD","GUESS","GUEST","GUIDE","GUILD","GUILT",
  "HAVEN","HEART","HEAVY","HEDGE","HELLO","HENCE","HONOR","HORSE","HOTEL","HOUSE","HUMAN","HUMOR",
  "IDEAL","IMAGE","IMPLY","INDEX","INDIE","INFER","INNER","INPUT","INTER","IRATE","ISSUE","IVORY",
  "JEWEL","JOINT","JUDGE","JUICE","KNACK","KNEEL","KNIFE","KNOCK","KNOLL",
  "LABEL","LABOR","LANCE","LARGE","LASER","LATER","LAUGH","LAYER","LEARN","LEASE","LEGAL","LEMON","LEVEL","LEVER","LIGHT","LIMIT","LINEN","LIVER","LOCAL","LODGE","LOGIC","LOOSE","LOVER","LOWER","LOYAL","LUNAR","LYING",
  "MAGIC","MAJOR","MANOR","MAPLE","MARCH","MARSH","MATCH","MAYOR","MEDAL","MEDIA","MERCY","MERGE","MERIT","METAL","METER","MIGHT","MINOR","MINUS","MIXED","MODEL","MONEY","MONTH","MORAL","MOTOR","MOUNT","MOUSE","MOUTH","MOVED","MOVIE","MUSIC","MYTHS",
  "NAVAL","NERVE","NEVER","NEWLY","NIGHT","NOBLE","NOISE","NORTH","NOTED","NOVEL","NURSE","NYLON",
  "OASIS","OCCUR","OCEAN","OFFER","OFTEN","OLIVE","ONSET","OPERA","ORBIT","ORDER","ORGAN","OTHER","OUGHT","OUTER","OVERT","OWNER",
  "PANEL","PANIC","PAPER","PARTY","PASTE","PATCH","PAUSE","PEACE","PEACH","PEARL","PEDAL","PENNY","PHASE","PHOTO","PIANO","PIECE","PILOT","PINCH","PITCH","PIXEL","PLACE","PLAIN","PLANE","PLANT","PLATE","PLEAD","PLAZA","PLUMB","PLUME","PLUMP","POINT","POLAR","POUND","POWER","PRESS","PRICE","PRIDE","PRIME","PRINT","PRIOR","PROBE","PRONE","PROOF","PROSE","PROUD","PROVE","PROXY","PULSE","PUNCH","PUPIL","PURSE",
  "QUEEN","QUEST","QUEUE","QUICK","QUIET","QUOTA","QUOTE",
  "RADAR","RADIO","RAISE","RALLY","RANGE","RAPID","RATIO","REACH","REACT","READY","REALM","REBEL","REFER","REIGN","RELAX","RELAY","RENAL","RENEW","REPLY","RIDER","RIDGE","RIFLE","RIGHT","RIGID","RISKY","RIVAL","RIVER","ROBIN","ROBOT","ROCKY","ROGUE","ROMAN","ROUGE","ROUGH","ROUND","ROUTE","ROYAL","RUGBY","RULER","RURAL",
  "SAINT","SALAD","SCALE","SCARE","SCENE","SCOPE","SCORE","SCOUT","SENSE","SERVE","SEVEN","SHADE","SHAFT","SHALL","SHAME","SHAPE","SHARE","SHARK","SHARP","SHEAR","SHELF","SHELL","SHIFT","SHIRE","SHIRT","SHOCK","SHORE","SHORT","SHOUT","SIGHT","SINCE","SIXTY","SIZED","SKATE","SKILL","SKULL","SLAVE","SLEEP","SLICE","SLIDE","SLOPE","SMALL","SMART","SMELL","SMILE","SMOKE","SOLAR","SOLID","SOLVE","SOUTH","SPACE","SPARE","SPARK","SPEAK","SPEAR","SPEED","SPELL","SPEND","SPENT","SPICE","SPIKE","SPINE","SPITE","SPLIT","SPOKE","SPOON","SPORT","SPRAY","SQUAD","STAFF","STAGE","STAIN","STAIR","STAKE","STALE","STALK","STALL","STAMP","STAND","STARE","START","STATE","STEAL","STEAM","STEEL","STEEP","STEER","STERN","STICK","STIFF","STILL","STING","STOCK","STOLE","STONE","STOOD","STOOL","STORE","STORM","STORY","STOVE","STRAP","STRAW","STRAY","STRIP","STUCK","STUDY","STUFF","STUMP","STYLE","SUITE","SURGE","SWAMP","SWARM","SWEAR","SWEEP","SWEET","SWEPT","SWIFT","SWING","SWIRL","SWORD",
  "TABLE","TASTE","TEACH","TEETH","TEMPO","THANK","THEFT","THEME","THERE","THICK","THIEF","THING","THINK","THIRD","THOSE","THREE","THREW","THROW","THUMB","TIDAL","TIGER","TIGHT","TIRED","TITLE","TODAY","TOKEN","TOPIC","TOTAL","TOUCH","TOUGH","TOWER","TOXIC","TRACE","TRACK","TRADE","TRAIL","TRAIN","TRAIT","TRASH","TREAT","TREND","TRIAL","TRIBE","TRICK","TROOP","TROUT","TRUCK","TRULY","TRUMP","TRUNK","TRUST","TRUTH","TULIP","TWICE","TWIST",
  "ULTRA","UNCLE","UNDER","UNION","UNITE","UNITY","UNTIL","UPPER","UPSET","URBAN","USAGE","USUAL","UTTER",
  "VAGUE","VALID","VALUE","VAPOR","VAULT","VERSE","VIDEO","VIGOR","VINYL","VIRAL","VIRUS","VISIT","VITAL","VIVID","VOCAL","VOICE","VOTER",
  "WASTE","WATCH","WATER","WEARY","WEAVE","WEDGE","WHEAT","WHEEL","WHERE","WHICH","WHILE","WHITE","WHOLE","WHOSE","WIDTH","WITCH","WOMAN","WORLD","WORRY","WORSE","WORST","WORTH","WOUND","WRECK","WRITE","WRONG","WROTE",
  "YACHT","YIELD","YOUNG","YOUTH","ZEBRA",
  // 6-letter
  "ABSORB","ACCENT","ACCEPT","ACCESS","ACCORD","ACCUSE","ACTIVE","ADJUST","ADMIRE","AFFIRM","AFFORD","AGENDA","ALIGHT","ALLIES","ANCHOR","ANNUAL","APPEAL","APPEAR","ARCHER","ASLEEP","ASSERT","ASSIGN","ASSIST","ASSUME","ASSURE","ATTACH","ATTACK","ATTEND","AUTUMN",
  "BACKER","BADGER","BARELY","BARONS","BARREL","BATTLE","BEACON","BEETLE","BELONG","BETRAY","BITTER","BLANCH","BLAZER","BLOUSE","BORDER","BOUNCE","BRANCH","BREACH","BRIDGE","BROKEN","BROKER","BRONZE","BUBBLE","BUCKET","BUDGET","BUFFER","BUNDLE","BURDEN","BURNED","BUTTER",
  "CACTUS","CALMER","CANCEL","CANDLE","CANNON","CANTON","CARBON","CAREER","CARPET","CASTLE","CATTLE","CAUSAL","CAVERN","CELLAR","CENTER","CEREAL","CHANCE","CHANGE","CHAPEL","CHARGE","CHASER","CHOOSE","CHURCH","CIRCLE","CLINIC","CLUMSY","COARSE","COBALT","COFFEE","COLUMN","COMBAT","COMEDY","COMMIT","COMMON","COMPEL","COMPLY","CONCUR","CONVEX","COOKIE","COPPER","CORNER","COSTLY","COTTON","COUNTY","COUPLE","COURSE","COUSIN","CRADLE","CRATER","CREATE","CREDIT","CRISIS","CRUISE","CUSTOM","CUTTER",
  "DAMAGE","DAMPEN","DANCER","DANGER","DARING","DEALER","DEBATE","DECADE","DECENT","DECIDE","DECODE","DECREE","DEFEAT","DEFEND","DEFUSE","DEGREE","DEMAND","DENIAL","DEPART","DEPLOY","DEPICT","DESERT","DESIGN","DESIRE","DETAIL","DETECT","DEVOTE","DIALOG","DIFFER","DIGEST","DILEMMA","DINNER","DIRECT","DISARM","DIVINE","DOMAIN","DONATE","DOUBLE","DRAGON","DRIVER","DUSTER",
  "EARNED","EASIER","EDITOR","EFFECT","EFFORT","EMBARK","EMPIRE","ENABLE","ENDURE","ENERGY","ENGAGE","ENGINE","ENJOYS","ENOUGH","ENSURE","ENTIRE","ERRAND","ESCAPE","ESTATE","EVOLVE","EXCEED","EXCITE","EXEMPT","EXHALE","EXPAND","EXPECT","EXPERT","EXPORT","EXPOSE","EXTENT","FABRIC",
  "FACTOR","FAIRLY","FALCON","FAMILY","FAMINE","FARMER","FATHOM","FAULTY","FELINE","FELLOW","FIERCE","FIGURE","FILTER","FINALE","FINGER","FISCAL","FLIGHT","FLORAL","FLOWER","FORBID","FORCES","FOREST","FORGET","FORMAL","FORMAT","FORMER","FOSSIL","FOSTER","FOURTH","FREEZE","FRIEND","FROZEN","FUMBLE","FUNGUS","FUSION","FUTILE","FUTURE",
  "GAINED","GALAXY","GALLOP","GAMBLE","GARAGE","GARDEN","GARLIC","GATHER","GENDER","GENIUS","GENTLE","GLOBAL","GOLDEN","GOSSIP","GOVERN","GRAVEL","GREASE","GROOVE","GUILTY","GUITAR",
  "HANDLE","HAPPEN","HARBOR","HARDER","HARKEN","HAZARD","HEALTH","HEAVEN","HEROIC","HOLLOW","HONEST","HORROR","HUDDLE","HUMBLE","HUNGER","HYBRID",
  "IGNORE","ILLUSE","IMPACT","IMPORT","IMPOSE","INCOME","INDOOR","INFANT","INFORM","INJECT","INJURY","INMATE","INSERT","INSIDE","INSIST","INSULT","INTACT","INTEND","INVENT","INVEST","INVITE","ISLAND",
  "JACKET","JARGON","JERSEY","JIGSAW","JOGGER","JOSTLE","JUGGLE","JUMBLE","JUNIOR","JUSTLY",
  "KIDNAP","KINDLE","KNIGHT","KITTEN",
  "LADDER","LARGER","LATELY","LAUNCH","LAWYER","LAYOUT","LEADER","LEAGUE","LEGACY","LENDER","LESSON","LETTER","LIGHTS","LIKELY","LINEAR","LINGER","LIQUID","LISTEN","LITTER","LITTLE","LIVELY","LOCKER","LONELY","LOVELY","LUMBER","LUXURY",
  "MAGNET","MAIDEN","MANAGE","MANNER","MANUAL","MARGIN","MARINE","MARKER","MARKET","MARVEL","MASTER","MATTER","MEADOW","MEDIUM","MEMBER","MEMOIR","MEMORY","MENTAL","MENTOR","MERGER","METHOD","MIDDLE","MIGHTY","MINGLE","MINUTE","MIRROR","MISERY","MODERN","MODEST","MONKEY","MORTAL","MOSAIC","MOSTLY","MOTHER","MOTION","MOTIVE","MUSTER","MUTTON","MYSELF","MYRIAD",
  "NAPKIN","NARROW","NATION","NATIVE","NATURE","NEARBY","NEARLY","NEATLY","NEEDLE","NEPHEW","NEURAL","NIMBLE","NORMAL","NOTICE","NOTIFY","NOTION","NOVICE","NUMBER","NURSED",
  "OBTAIN","OCCUPY","OFFEND","OFFICE","OFFSET","ONLINE","OPENER","OPPOSE","OPTION","ORACLE","ORANGE","ORCHID","ORDEAL","ORIENT","ORIGIN","OUTLET","OUTPUT","OUTRUN",
  "PALACE","PARADE","PARCEL","PARENT","PARODY","PATROL","PATRON","PATTER","PAUSE","PENCIL","PEOPLE","PERIOD","PERMIT","PERSON","PHRASE","PICKET","PIGEON","PILLAR","PILLOW","PLAGUE","PLANET","PLAYER","PLEDGE","PLIANT","PLUNGE","POCKET","POETRY","POISON","POLICE","POLICY","POLISH","POLITE","PONDER","PORTAL","POSTER","POTATO","POTION","POWDER","PRAISE","PRAYER","PREFER","PREFIX","PRIEST","PRINCE","PRISON","PROFIT","PROMPT","PROPEL","PROVEN","PUBLIC","PUDDLE","PUNISH","PUPPET","PURSUE","PUZZLE",
  "QUARRY","QUENCH","QUIVER",
  "RACIAL","RACKET","RANDOM","RANGER","RARELY","RARITY","RATHER","RATING","RATION","RAVINE","REASON","RECALL","RECENT","RECKON","RECORD","REDUCE","REFORM","REFUGE","REFUND","REGARD","REGIME","REGION","REJECT","RELATE","RELIEF","RELISH","REMAIN","REMEDY","REMOTE","REMOVE","RENDER","RENTAL","REPAIR","REPEAT","REPORT","RESCUE","RESIGN","RESIST","RESORT","RESULT","RETAIL","RETAIN","RETIRE","RETURN","REVEAL","REVIEW","REVOLT","REWARD","RIDDLE","RITUAL","ROBUST","ROCKET","ROTATE","RULING","RUMBLE","RUSTIC",
  "SACRED","SAFARI","SAFELY","SAFETY","SALUTE","SAMPLE","SANITY","SAVAGE","SCENIC","SCHEME","SCHOOL","SCRIPT","SCROLL","SEARCH","SEASON","SECOND","SECRET","SECURE","SELECT","SENSOR","SEQUEL","SERIAL","SETTLE","SEVERE","SHADOW","SHIELD","SIGNAL","SILENT","SILVER","SIMPLE","SINGLE","SISTER","SKETCH","SLIGHT","SNATCH","SOCIAL","SOFTEN","SOLVER","SORROW","SOURCE","SPEECH","SPHERE","SPIRIT","SPLICE","SPONGE","SPREAD","SPRING","SQUARE","STABLE","STANCE","STAPLE","STATUS","STEADY","STOLEN","STRAIN","STRAND","STREAM","STREET","STRICT","STRIDE","STRIKE","STRING","STROKE","STRONG","STRUCK","SUBMIT","SUBTLE","SUCKER","SUDDEN","SUFFER","SUMMER","SUMMIT","SUNKEN","SUPERB","SUPPLY","SURELY","SURVEY","SWITCH","SYMBOL","SYSTEM",
  "TACKLE","TALENT","TARGET","TEMPLE","TENANT","TENDER","TERROR","THIRST","THORNS","THREAD","THRILL","THRIVE","THRONE","TIMBER","TISSUE","TONGUE","TOWARD","TRENCH","TRIPLE","TROPHY","TUNDRA","TUNNEL","TURTLE","TWELVE","TYRANT",
  "UNFAIR","UNFOLD","UNIQUE","UNITED","UNLIKE","UNLOCK","UNREST","UNVEIL","UPDATE","UPHOLD","URGENT","USABLE","UTMOST",
  "VACANT","VALLEY","VANDAL","VANISH","VASTLY","VECTOR","VELVET","VENDOR","VERBAL","VERIFY","VESSEL","VICTIM","VIEWER","VIRGIN","VIRTUE","VISION","VOLUME","VOYAGE",
  "WAITER","WALKER","WALLET","WANDER","WARMTH","WEALTH","WEAPON","WEEKLY","WEIGHT","WIDGET","WINDOW","WINNER","WINTER","WISDOM","WITHIN","WONDER","WORKER","WORTHY","WRITER",
  "YEARLY","ZENITH","ZIGZAG",
  // 7-letter
  "ABANDON","ABILITY","ABOLISH","ABSENCE","ABSTAIN","ACQUIRE","ALREADY","AMAZING","ANCIENT","ANGULAR","APOLOGY","ARRANGE","AVERAGE","AWESOME",
  "BALANCE","BARGAIN","BARRIER","BATTERY","BELIEVE","BENEATH","BENEFIT","BETWEEN","BILLION","BONDAGE","BOROUGH","BREAKER","BREATHE","BROUGHT","BUILDER","BURNING",
  "CABINET","CALCIUM","CALIBER","CAPABLE","CAPITAL","CAPTAIN","CAPTURE","CAREFUL","CATALOG","CAUTION","CEILING","CENTRAL","CERTAIN","CHAMBER","CHANNEL","CHAPTER","CHARITY","CHARTER","CHIMNEY","CIRCUIT","CITIZEN","CLIMATE","CLUSTER","COASTAL","COLLECT","COMBINE","COMFORT","COMMAND","COMMENT","COMPANY","COMPARE","COMPASS","COMPETE","COMPLEX","COMPOSE","COMPUTE","CONCEPT","CONCERN","CONDEMN","CONDUCT","CONFESS","CONFIDE","CONFIRM","CONFUSE","CONNECT","CONQUER","CONSIST","CONSULT","CONSUME","CONTACT","CONTAIN","CONTENT","CONTEST","CONTEXT","CONTROL","CONVERT","CORRECT","COUNCIL","COUNTER","COUNTRY","COURAGE","CREATOR","CULTURE","CURIOUS","CURRENT","CURTAIN","CUSTOMS",
  "DAYLIGHT","DEALING","DECLINE","DEFAULT","DEFENCE","DELIVER","DENSITY","DESPAIR","DESPITE","DESTINY","DETAILS","DEVELOP","DEVOTED","DIAMOND","DIGITAL","DISABLE","DISCARD","DISEASE","DISGUST","DISMISS","DISPLAY","DISPUTE","DISTANT","DISTURB","DIVERSE","DIVIDER","DOLPHIN","DORMANT","DROUGHT","DYNASTY",
  "EARNING","EASTERN","ECLIPSE","ECONOMY","EDITION","EDUCATE","ELDERLY","ELEMENT","EMBRACE","EMOTION","EMPEROR","ENDLESS","ENGAGED","ENHANCE","ENQUIRE","ENVIRON","EPISODE","ESSENCE","ETERNAL","EVIDENT","EXAMINE","EXAMPLE","EXCITED","EXECUTE","EXHAUST","EXHIBIT","EXPENSE","EXPIRED","EXPLAIN","EXPLOIT","EXPLORE","EXPRESS","EXTRACT","EXTREME",
  "FACTORY","FACULTY","FAILURE","FANTASY","FASHION","FEATURE","FICTION","FIGHTER","FINANCE","FINDING","FISHING","FITNESS","FIXTURE","FLANNEL","FOOLISH","FOREIGN","FOREVER","FORMULA","FORTUNE","FORWARD","FOUNDER","FREEDOM","FREIGHT","FULFILL","FUNDING","FURNISH","FURTHER","FUTILE",
  "GALLERY","GATEWAY","GENERAL","GENUINE","GLACIER","GLIMPSE","GRAMMAR","GRANITE","GREATLY","GROCERY","GROWING","HABITAT","HALFWAY","HALCYON","HANDFUL","HAPPILY","HARBOUR","HARMFUL","HARMONY","HARVEST","HEALTHY","HEARING","HELPFUL","HEROISM","HIGHWAY","HIMSELF","HISTORY","HOLIDAY","HOPEFUL","HORIZON","HOSTILE","HOUSING","HOWEVER","HUNDRED","HUNTING","HUSBAND",
  "IMAGINE","IMMENSE","ILLEGAL","IMPETUS","IMPRESS","IMPROVE","INCLUDE","INDEXED","INFLATE","INHERIT","INITIAL","INSPIRE","INSTALL","INSTANT","INSTEAD","INSULIN","INTERIM","INVALID","INWARDS","ISOLATE",
  "JOURNAL","JOURNEY","JUBILEE","JUSTICE","JUSTIFY",
  "KEYWORD","KILLING","KINGDOM","KITCHEN",
  "LANDING","LARGELY","LASTING","LEADING","LEARNED","LECTURE","LEISURE","LIBRARY","LIMITED","LITERAL","LOCALLY","LONGING","LOYALTY",
  "MACHINE","MAGICAL","MILLION","MINERAL","MINIMUM","MIRACLE","MISSION","MIXTURE","MONITOR","MONSTER","MONTHLY","MORNING","MYSTERY",
  "NATURAL","NEITHER","NETWORK","NEUTRAL","NOTABLE","NOTHING","NOWHERE","NUCLEAR","NURSERY",
  "OBVIOUS","OFFLINE","OPINION","OPTIMAL","ORBITAL","ORGANIC","OUTLINE","OUTLOOK","OUTSIDE","OVERALL",
  "PACKAGE","PAINTER","PARKING","PARTIAL","PARTNER","PASSAGE","PASSIVE","PATIENT","PATTERN","PAYMENT","PENALTY","PENSION","PERCENT","PERFECT","PERHAPS","PIONEER","PLASTIC","PLATTER","PLEASED","POPULAR","PORTION","POTTERY","POVERTY","PRECEDE","PREDICT","PREMIUM","PREPARE","PRESENT","PRESUME","PRETEND","PREVENT","PRIMARY","PRINTER","PRIVACY","PRIVATE","PROBLEM","PROCEED","PRODUCE","PRODUCT","PROFILE","PROGRAM","PROJECT","PROMISE","PROMOTE","PROTECT","PROTEIN","PROTEST","PROVIDE","PUBLISH","PURSUIT","PUZZLER",
  "QUALIFY","QUARREL","QUARTER","QUICKLY",
  "RADICAL","RAILWAY","RAINBOW","REALITY","REBUILD","RECEIPT","RECEIVE","RECOVER","RECRUIT","REFLECT","REFUGEE","REGULAR","RELATED","RELEASE","REMAINS","REMOVAL","RENEWAL","REPLACE","RESOLVE","RESPECT","RESPOND","RESTORE","RETREAT","RETURNS","REUNION","REVERSE","REVIVAL","REVOLVE","ROUTINE","ROYALTY",
  "SALVAGE","SCATTER","SCENERY","SCHOLAR","SECTION","SEGMENT","SERIOUS","SERVICE","SESSION","SETTLER","SHELTER","SILENCE","SIMILAR","SINCERE","SKILLED","SOCIETY","SOLDIER","SOMEHOW","SPONSOR","STARTUP","STATION","STORAGE","STRANGE","STUDENT","SUBJECT","SUCCESS","SUGGEST","SUMMARY","SUNRISE","SUPPORT","SURFACE","SURGEON","SURPLUS","SURVIVE","SUSPECT","SUSTAIN","SYMPTOM",
  "TACTFUL","THEATRE","THERAPY","THEREBY","THOUGHT","THROUGH","THUNDER","TOBACCO","TONIGHT","TOURISM","TOURIST","TRADING","TRAFFIC","TRAINER","TRANSIT","TRIGGER","TRIUMPH","TROUBLE","TRUSTED","TURNING","TUITION","TYPICAL",
  "UNDERGO","UNHAPPY","UNIFORM","UNKNOWN","UNRAVEL","UNUSUAL","UPGRADE","UTILITY",
  "VACANCY","VACCINE","VARIETY","VENTURE","VERDICT","VERSION","VETERAN","VIBRANT","VICTORY","VILLAGE","VINTAGE","VIOLENT","VIRTUAL","VISIBLE","VOLCANO","VOLTAGE","VOUCHER",
  "WARNING","WARFARE","WARRIOR","WEATHER","WEBSITE","WELCOME","WELFARE","WESTERN","WHETHER","WHISPER","WHOEVER","WILLING","WINDING","WRITTEN",
  // 8-letter
  "ABSOLUTE","ABSTRACT","ACCURATE","ACHIEVED","ACTUALLY","ADDITION","ADEQUATE","ADJUSTED","ADVANCED","ADVOCATE","ALTHOUGH","ANALYSIS","ANNOUNCE","ANNUALLY","ANYWHERE","APPARENT","APPETITE","APPROVAL","BALANCED","BATHROOM","BECOMING","BIRTHDAY","CEREMONY","CHAMPION","CHANGING","CHEMICAL","CHILDREN","CLIMBING","CLOTHING","COLLAPSE","COLONIAL","COMBINED","COMPLETE","COMPOSED","COMPOUND","COMPUTER","CONCLUDE","CONCRETE","CONFLICT","CONGRESS","CONSIDER","CONSUMER","CONTINUE","CONTRACT","CONTRAST","CONVINCE","CORRIDOR","CRIMINAL","CRITICAL","CULTURAL","CURRENCY","CUSTOMER","CYLINDER",
  "DATABASE","DEADLINE","DECEMBER","DECISION","DECISIVE","DECLARED","DECLINED","DECREASE","DEDICATE","DEFEATED","DEFENDER","DEFINITE","DELICATE","DELIVERY","DEMANDED","DEMOCRAT","DESCRIBE","DESIGNER","DETAILED","DETECTED","DIALOGUE","DINOSAUR","DIPLOMAT","DISABLED","DISASTER","DISCOUNT","DISCOVER","DISORDER","DISPATCH","DISTINCT","DISTRICT","DIVISION","DOCTRINE","DOCUMENT","DOMESTIC","DOMINANT","DONATION","DOWNTOWN","DRAMATIC","DURATION",
  "EARNINGS","ECONOMIC","EDUCATED","ELECTION","ELEGANCE","ELEVATED","ELIGIBLE","EMISSION","EMOTIONAL","EMPHASIS","EMPLOYEE","EMPLOYER","ENCLOSED","ENCODING","ENORMOUS","ENSEMBLE","ENVELOPE","ENTIRELY","ENTRANCE","ESTIMATE","EVALUATE","EVIDENCE","EXCHANGE","EXCITING","EXERCISE","EXISTING","EXPECTED","EXPEDITE","EXPLICIT","EXPORTER","EXTENDED","EXTERNAL","ABSOLUTE",
  "FABULOUS","FACILITY","FAMILIAR","FAVORITE","FEARLESS","FEATURED","FEEDBACK","FESTIVAL","FIGHTING","FINISHED","FLEXIBLE","FLOURISH","FOOTBALL","FORECAST","FORMERLY","FOURTEEN","FRACTION","FRAGMENT","FRAMWORK","FREQUENT","FRIENDLY","FRONTIER","FUNCTION","FURNITUE",
  "GENERATE","GENEROUS","GENOCIDE","GLANCING","GRATEFUL","GUARDIAN","GUIDANCE",
  "HANDLING","HANDSOME","HAPPENED","HARDWARE","HEADLINE","HESITATE","HIGHLAND","HISTORIC","HOMEWORK","HONESTLY","HORRIBLE","HOSPITAL","HUMANITY","HUMOROUS","HUSBAND",
  "IDENTIFY","ILLUSION","IMAGINED","IMPERIAL","INCIDENT","INCREASE","INDICATE","INDIRECT","INDUSTRY","INFERIOR","INFORMED","INHERENT","INNOCENT","INSTANCE","INTEGRAL","INTENDED","INTERACT","INTEREST","INTERIOR","INTERNAL","INTIMATE","INVASION","INVENTOR","INVESTOR","INVOLVED","ISOLATED",
  "JUDGMENT","JUNCTION",
  "KEYBOARD","KNOCKOUT",
  "LANGUAGE","LAUGHTER","LAVENDER","LAUNCHED","LANDLORD","LEARNING","LEFTOVER","LIFETIME","LIKEWISE","LISTENED","LITERARY","LOCATION","MAGNETIC","MAINTAIN","MAJORITY","MANAGING","MANIFEST","MARATHON","MARGINAL","MARITIME","MARRIAGE","MATERIAL","MAXIMIZE","MEASURED","MECHANIC","MEDIEVAL","MEMBRANE","MEMORIAL","MERCHANT","MIDNIGHT","MILITARY","MINIMIZE","MINISTER","MINORITY","MODERATE","MOISTURE","MOLECULE","MONETARY","MONOPOLY","MORTGAGE","MOUNTAIN","MOVEMENT","MULTIPLY","MUNDANE","MUSHROOM","MUTATION","MYSTICAL",
  "NATIONAL","NAVIGATE","NEGATIVE","NEIGHBOR","NEWCOMER","NIGHTCAP","NOMINATE","NORMALLY","NOTEBOOK","NUMEROUS",
  "OBEDIENT","OBJECTED","OBSERVED","OBSTACLE","OBTAINED","OCCASION","OCCUPIED","OCCURRED","OFFERING","OFFICIAL","OFFSHORE","OPPONENT","OPPOSITE","OPTIMIST","OPTIONAL","ORDINARY","ORGANIZE","ORIGINAL","OUTBURST","OUTDOORS","OUTLINED","OVERCOME","OVERHEAD","OVERLOOK","OVERTURN",
  "PAINTING","PANDEMIC","PARADISE","PARALLEL","PARENTAL","PATIENCE","PEACEFUL","PECULIAR","PERCEIVE","PERIODIC","PERSONAL","PERSUADE","PHYSICAL","PILGRIMAGE","PLANNING","PLATFORM","PLEASANT","PLEASURE","PLUNGING","POETICAL","POINTING","POLISHED","POLITICS","POPULACE","PORTLAND","POSITION","POSITIVE","POSSIBLE","POSTPONE","POWERFUL","PRACTICE","PRECIOUS","PREPARED","PRESENCE","PRESERVE","PRESSING","PRESSURE","PRESTIGE","PREVIOUS","PRINCESS","PRIORITY","PROBABLY","PRODUCER","PROFOUND","PROGRESS","PROPERLY","PROPERTY","PROPOSAL","PROSPECT","PROVINCE","PUBLICLY","PUNISHED","PURCHASE","PURSUING","QUANTITY","QUARTERS","QUESTION",
  "RATIONAL","REACTION","READABLE","RECEIVED","RECENTLY","RECKLESS","RECORDER","RECOVERY","REFERRED","REGIONAL","REGISTER","REGULATE","RELATION","RELATIVE","RELEVANT","RELEASED","RELIGION","REMAINED","REMEMBER","REMINDED","RENOWNED","REPEATED","REPORTED","REPUBLIC","REQUIRED","RESEARCH","RESERVED","RESIDENT","RESIGNED","RESOLVED","RESOURCE","RESPONSE","RESTLESS","RESTORED","RESTRICT","RESULTED","RETIRING","RETURNED","REVEALED","REVISION","RIGOROUS","ROMANTIC","ROTATION",
  "SANCTION","SANDWICH","SCENARIO","SCHEDULE","SCHOLARS","SCRUTINY","SEASONAL","SECONDLY","SECRETLY","SECURITY","SELECTED","SEMESTER","SENSIBLE","SENTENCE","SEPARATE","SEQUENCE","SERGEANT","SEVERELY","SHIPPING","SHOCKING","SHOOTING","SHORTAGE","SHOULDER","SHOWCASE","SHUTDOWN","SIMPLIFY","SINCERELY","SITUATED","SKELETON","SLEEPING","SOFTWARE","SOMEBODY","SOMETIME","SOUTHERN","SPANNING","SPECIFIC","SPECTRUM","SPENDING","SPORTING","SQUEEZED","STANDARD","STANDING","STIMULUS","STOPPING","STRAIGHT","STRANGER","STRATEGY","STRENGTH","STRICTLY","STRIKING","STRONGLY","STRUGGLE","STUNNING","SUBURBAN","SUDDENLY","SUITABLE","SUPERIOR","SUPPLIED","SURPRISE","SURGICAL","SURROUND","SURVIVAL","SUSPENSE","SWIMMING","SYMBOLIC","SYMMETRY","SYMPATHY","SYNDROME",
  "TANGIBLE","TEACHING","TEMPORAL","TERMINAL","TERRIFIC","TERMINAL","THANKFUL","THINKING","THOROUGH","THOUSAND","TOGETHER","TOMORROW","TORTOISE","TOUCHING","TRAILING","TRAINING","TRANSFER","TREASURE","TREATING","TRIBUNAL","TROPICAL","ULTIMATE","UMBRELLA","UNCOMMON","UNDERWAY","UNIVERSE","UNLIKELY","UNLOCKED","UNNOTICE","UNSTABLE","UPCOMING","UPDATING","UPHEAVAL","UPRISING","VACATION","VALUABLE","VARIABLE","VELOCITY","VERTICAL","VIOLENCE","VOLATILE","VOLCANIC","VOLUNTER","WEAKNESS","WHATEVER","WHEREVER","WIRELESS","WITHDRAW","WOODLAND","WORKSHOP","YOURSELF",
];

// Build a sorted-letter index for fast anagram lookup
function sortLetters(word: string): string {
  return word.split("").sort().join("");
}

const ANAGRAM_INDEX: Map<string, string[]> = new Map();
for (const word of WORD_LIST) {
  const key = sortLetters(word);
  const arr = ANAGRAM_INDEX.get(key);
  if (arr) {
    arr.push(word);
  } else {
    ANAGRAM_INDEX.set(key, [word]);
  }
}

function findAnagrams(input: string, filterLength: number | null): string[] {
  const clean = input.toUpperCase().replace(/[^A-Z]/g, "");
  if (clean.length < 2) return [];

  if (filterLength) {
    // Find anagrams of exact length from the input letters (subset anagrams)
    const results: string[] = [];
    const inputSorted = clean.split("").sort();

    for (const [key, words] of ANAGRAM_INDEX) {
      if (key.length !== filterLength) continue;
      // Check if key letters are a subset of input letters
      const available = [...inputSorted];
      let valid = true;
      for (const ch of key) {
        const idx = available.indexOf(ch);
        if (idx === -1) {
          valid = false;
          break;
        }
        available.splice(idx, 1);
      }
      if (valid) {
        for (const w of words) {
          if (w !== clean) results.push(w);
        }
      }
    }
    return results.sort().slice(0, 100);
  }

  // Default: find exact-length anagrams + subset anagrams
  const key = sortLetters(clean);
  const exact = ANAGRAM_INDEX.get(key)?.filter((w) => w !== clean) || [];

  // Also find shorter words from the same letters
  const shorter: string[] = [];
  for (const [k, words] of ANAGRAM_INDEX) {
    if (k.length >= clean.length || k.length < 3) continue;
    const available = [...key];
    let valid = true;
    for (const ch of k) {
      const idx = available.indexOf(ch);
      if (idx === -1) {
        valid = false;
        break;
      }
      available.splice(idx, 1);
    }
    if (valid) {
      for (const w of words) shorter.push(w);
    }
  }

  return [...exact, ...shorter.sort()].slice(0, 100);
}

export default function AnagramSolver() {
  const [input, setInput] = useState("");
  const [filterLength, setFilterLength] = useState<number | null>(null);

  const results = useMemo(() => {
    return findAnagrams(input, filterLength);
  }, [input, filterLength]);

  const clean = input.toUpperCase().replace(/[^A-Z]/g, "");
  const hasInput = clean.length >= 2;

  // Group results by length
  const grouped = useMemo(() => {
    const map = new Map<number, string[]>();
    for (const w of results) {
      const len = w.length;
      const arr = map.get(len);
      if (arr) arr.push(w);
      else map.set(len, [w]);
    }
    return Array.from(map.entries()).sort((a, b) => b[0] - a[0]);
  }, [results]);

  return (
    <div className="rounded-2xl border border-border bg-card p-4 shadow-sm sm:p-6">
      <h2 className="font-heading text-lg font-bold text-foreground">
        Anagram Solver
      </h2>
      <p className="mt-1 text-sm text-muted-foreground">
        Enter letters and find all possible words. Use the length filter to
        narrow results.
      </p>

      <div className="mt-4 grid gap-3">
        <div>
          <label
            htmlFor="anagram-input"
            className="mb-1 block text-xs font-medium text-muted-foreground"
          >
            Enter your letters
          </label>
          <input
            id="anagram-input"
            type="text"
            placeholder="e.g. LISTEN"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            className="w-full rounded-lg border-2 border-border bg-background px-3 py-2.5 font-mono text-lg font-bold uppercase tracking-widest text-foreground placeholder:text-muted-foreground/40 placeholder:font-normal placeholder:text-sm placeholder:tracking-normal placeholder:normal-case focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary sm:max-w-sm"
            autoComplete="off"
            autoCorrect="off"
            spellCheck={false}
          />
        </div>

        {hasInput && (
          <div>
            <label className="mb-1 block text-xs font-medium text-muted-foreground">
              Filter by word length
            </label>
            <div className="flex flex-wrap gap-1.5">
              <button
                type="button"
                onClick={() => setFilterLength(null)}
                className={`rounded-lg px-3 py-1.5 text-sm font-medium transition ${
                  filterLength === null
                    ? "bg-primary text-primary-foreground"
                    : "bg-muted text-muted-foreground hover:bg-primary/10 hover:text-primary"
                }`}
              >
                All
              </button>
              {Array.from(
                { length: Math.min(clean.length, 8) - 2 },
                (_, i) => i + 3
              ).map((n) => (
                <button
                  key={n}
                  type="button"
                  onClick={() => setFilterLength(n)}
                  className={`rounded-lg px-3 py-1.5 text-sm font-medium transition ${
                    filterLength === n
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted text-muted-foreground hover:bg-primary/10 hover:text-primary"
                  }`}
                >
                  {n}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {hasInput && (
        <div className="mt-5">
          <p className="text-xs font-medium text-muted-foreground">
            {results.length === 0
              ? "No anagrams found."
              : `${results.length}${results.length === 100 ? "+" : ""} word${results.length !== 1 ? "s" : ""} found`}
          </p>
          {grouped.map(([len, words]) => (
            <div key={len} className="mt-3">
              <p className="mb-1.5 text-xs font-semibold text-muted-foreground">
                {len}-letter words ({words.length})
              </p>
              <div className="flex flex-wrap gap-1.5">
                {words.map((word) => (
                  <span
                    key={word}
                    className="rounded-lg border border-border bg-background px-2.5 py-1 font-mono text-sm font-medium text-foreground"
                  >
                    {word}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {!hasInput && (
        <p className="mt-4 text-xs text-muted-foreground">
          Type at least 2 letters to start finding anagrams. For example, type
          LISTEN to find SILENT, TINSEL, ENLIST, and more.
        </p>
      )}
    </div>
  );
}
